.TH "src/eu/aniketos/srcm/mapping/ Directory Reference" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/eu/aniketos/srcm/mapping/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIsA\&.java\fP"
.br
.ti -1c
.RI "file \fBMapping\&.java\fP"
.br
.ti -1c
.RI "file \fBPlays\&.java\fP"
.br
.ti -1c
.RI "file \fBRelatesTo\&.java\fP"
.br
.ti -1c
.RI "file \fBRepresents\&.java\fP"
.br
.in -1c
