.TH "src/eu/aniketos/srcm/ Directory Reference" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/eu/aniketos/srcm/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBalgorithms\fP"
.br
.ti -1c
.RI "directory \fBfunctional\fP"
.br
.ti -1c
.RI "directory \fBmapping\fP"
.br
.ti -1c
.RI "directory \fBSRS\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBActivator\&.java\fP"
.br
.ti -1c
.RI "file \fBSRCM\&.java\fP"
.br
.in -1c
