.TH "eu.aniketos.srcm.mapping.RelatesTo" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.mapping.RelatesTo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGoal\fP \fBgetGoal\fP ()"
.br
.ti -1c
.RI "void \fBsetGoal\fP (\fBGoal\fP goal)"
.br
.ti -1c
.RI "\fBActivity\fP \fBgetActivity\fP ()"
.br
.ti -1c
.RI "void \fBsetActivity\fP (\fBActivity\fP activity)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the relates-to relation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBActivity\fP eu\&.aniketos\&.srcm\&.mapping\&.RelatesTo\&.getActivity ()"
Getter of the activity 
.PP
\fBReturns:\fP
.RS 4
the activity in the class 
.RE
.PP

.SS "\fBGoal\fP eu\&.aniketos\&.srcm\&.mapping\&.RelatesTo\&.getGoal ()"
Getter of the goal 
.PP
\fBReturns:\fP
.RS 4
the goal in the class 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.mapping\&.RelatesTo\&.setActivity (\fBActivity\fPactivity)"
Setter of the activity 
.PP
\fBParameters:\fP
.RS 4
\fIactivity\fP the activity that have to be set 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.mapping\&.RelatesTo\&.setGoal (\fBGoal\fPgoal)"
Setter of the goal 
.PP
\fBParameters:\fP
.RS 4
\fIgoal\fP the goal that have to be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
