.TH "eu.aniketos.srcm.SRS.Actor" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.SRS.Actor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBeu\&.aniketos\&.SecureBPMN\&.Lane\fP, \fBeu\&.aniketos\&.SecureBPMN\&.Participant\fP, \fBeu\&.aniketos\&.SecureBPMN\&.Pool\fP, \fBeu\&.aniketos\&.srcm\&.SRS\&.Agent\fP, and \fBeu\&.aniketos\&.srcm\&.SRS\&.Role\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manage the \fBSRS\fP actor elements 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String eu\&.aniketos\&.srcm\&.SRS\&.Actor\&.getId ()"
Getter of the actor ID 
.PP
\fBReturns:\fP
.RS 4
the actor ID 
.RE
.PP

.SS "String eu\&.aniketos\&.srcm\&.SRS\&.Actor\&.getName ()"
Getter of the actor name 
.PP
\fBReturns:\fP
.RS 4
the actor name 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Lane\fP, \fBeu\&.aniketos\&.SecureBPMN\&.Pool\fP, and \fBeu\&.aniketos\&.SecureBPMN\&.Participant\fP\&.
.SS "void eu\&.aniketos\&.srcm\&.SRS\&.Actor\&.setId (Stringid)"
Setter of the actor ID 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP of the actor 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.SRS\&.Actor\&.setName (Stringname)"
Setter of the actor name 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP of the actor 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Lane\fP, \fBeu\&.aniketos\&.SecureBPMN\&.Pool\fP, and \fBeu\&.aniketos\&.SecureBPMN\&.Participant\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
