.TH "eu.aniketos.wp4.SRS.Resource" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.Resource \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBeu\&.aniketos\&.wp4\&.SRS\&.Document\fP, and \fBeu\&.aniketos\&.wp4\&.SRS\&.Information\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manage the \fBSRS\fP resource Element 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String eu\&.aniketos\&.wp4\&.SRS\&.Resource\&.getId ()"
Getter of the resource ID 
.PP
\fBReturns:\fP
.RS 4
the resource ID 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Variable\fP\&.
.SS "String eu\&.aniketos\&.wp4\&.SRS\&.Resource\&.getName ()"
Getter of the goal name 
.PP
\fBReturns:\fP
.RS 4
the goal name 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Variable\fP\&.
.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Resource\&.setId (Stringid)"
Setter of the resource ID 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP the resource ID 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Variable\fP\&.
.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Resource\&.setName (Stringname)"
Setter of the resource name 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP name of the resource 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Variable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
