.TH "eu.aniketos.srcm.functional.SecReqInst" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.functional.SecReqInst \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This class manages the Security requirements instantiation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
