.TH "eu.aniketos.wp4.SRS.PartOf" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.PartOf \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResource\fP \fBgetContents\fP ()"
.br
.ti -1c
.RI "void \fBsetContent\fP (\fBResource\fP content)"
.br
.ti -1c
.RI "\fBResource\fP \fBgetContainer\fP ()"
.br
.ti -1c
.RI "void \fBsetContainer\fP (\fBResource\fP container)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the Part-Of relation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBResource\fP eu\&.aniketos\&.wp4\&.SRS\&.PartOf\&.getContainer ()"
Getter of the 'container' part of the relation 
.PP
\fBReturns:\fP
.RS 4
the 'container' part of the relation 
.RE
.PP

.SS "\fBResource\fP eu\&.aniketos\&.wp4\&.SRS\&.PartOf\&.getContents ()"
Getter of the 'contents' part of the relation 
.PP
\fBReturns:\fP
.RS 4
the 'contents' part of the relation 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.PartOf\&.setContainer (\fBResource\fPcontainer)"
Setter of the 'container' part of the relation 
.PP
\fBParameters:\fP
.RS 4
\fIcontainer\fP the 'container' that has to be set 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.PartOf\&.setContent (\fBResource\fPcontent)"
Setter of the 'contents' part of the relation 
.PP
\fBParameters:\fP
.RS 4
\fIcontent\fP the 'content' that has to be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
