.TH "eu.aniketos.SecureBPMN.Event" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.SecureBPMN.Event \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeu\&.aniketos\&.SecureBPMN\&.Element\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBType\fP \fBgetType\fP ()"
.br
.ti -1c
.RI "void \fBsetType\fP (\fBType\fP type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the event Business Process element\&. 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBType\fP eu\&.aniketos\&.SecureBPMN\&.Event\&.getType ()"
Getter of the type of the event 
.PP
\fBReturns:\fP
.RS 4
type of the event 
.RE
.PP

.SS "void eu\&.aniketos\&.SecureBPMN\&.Event\&.setType (\fBType\fPtype)"
Setter of the type of the event 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP of the event 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
