.TH "eu.aniketos.SecureBPMN.Participant" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.SecureBPMN.Participant \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeu\&.aniketos\&.srcm\&.SRS\&.Actor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the \fBParticipant\fP business process element\&. It extends actor class because, at the instantiation phase, all actor elements will be transformed in Business Process elements 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String eu\&.aniketos\&.SecureBPMN\&.Participant\&.getName ()"
Getter of the actor name 
.PP
\fBReturns:\fP
.RS 4
the actor name 
.RE
.PP

.PP
Reimplemented from \fBeu\&.aniketos\&.srcm\&.SRS\&.Actor\fP\&.
.SS "void eu\&.aniketos\&.SecureBPMN\&.Participant\&.setName (Stringname)"
Setter of the actor name 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP of the actor 
.RE
.PP

.PP
Reimplemented from \fBeu\&.aniketos\&.srcm\&.SRS\&.Actor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
