.TH "eu.aniketos.wp4.SRS.SecurityNeed" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.SecurityNeed \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBeu\&.aniketos\&.wp4\&.SRS\&.NonDisclosure\fP, \fBeu\&.aniketos\&.wp4\&.SRS\&.NonModification\fP, \fBeu\&.aniketos\&.wp4\&.SRS\&.NonProduction\fP, \fBeu\&.aniketos\&.wp4\&.SRS\&.NonRepudiation\fP, \fBeu\&.aniketos\&.wp4\&.SRS\&.NonUsage\fP, and \fBeu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\fP\&.
.SH "Detailed Description"
.PP 
This class manages postcondition (security need) \fBSRS\fP element 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
