.TH "eu.aniketos.wp4.SRS.Role" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.Role \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeu\&.aniketos\&.wp4\&.SRS\&.Actor\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class manage the \fBSRS\fP role element 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
