.TH "eu.aniketos.srcm.functional.BPM" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.functional.BPM \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBeu\&.aniketos\&.SecureBPMN\&.EABPM\fP\&.
.SH "Detailed Description"
.PP 
This class manages the \fBBPM\fP 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
