.TH "eu.aniketos.srcm.functional.AuthCheck" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.functional.AuthCheck \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcreateAuthTable\fP (\fBSRS\fP srs, HashSet< \fBCommitment\fP > undecCommitmentList, Vector< ActorVarOperation > operations)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages authorization algorithms and the authorization table 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void eu\&.aniketos\&.srcm\&.functional\&.AuthCheck\&.createAuthTable (\fBSRS\fPsrs, HashSet< \fBCommitment\fP >undecCommitmentList, Vector< ActorVarOperation >operations)\fC [static]\fP"
\fBParameters:\fP
.RS 4
\fIsrs\fP 
.br
\fIundecCommitmentList\fP 
.br
\fIoperations\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
