.TH "eu.aniketos.srcm.mapping.Represents" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.mapping.Represents \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocument\fP \fBgetDocument\fP ()"
.br
.ti -1c
.RI "void \fBsetDocument\fP (\fBDocument\fP document)"
.br
.ti -1c
.RI "\fBVariable\fP \fBgetVariable\fP ()"
.br
.ti -1c
.RI "void \fBsetVariable\fP (\fBVariable\fP variable)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the \fBRepresents\fP relation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBDocument\fP eu\&.aniketos\&.srcm\&.mapping\&.Represents\&.getDocument ()"
Gette of the document 
.PP
\fBReturns:\fP
.RS 4
the document in the class 
.RE
.PP

.SS "\fBVariable\fP eu\&.aniketos\&.srcm\&.mapping\&.Represents\&.getVariable ()"
Getter of the variable 
.PP
\fBReturns:\fP
.RS 4
the variable in the class 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.mapping\&.Represents\&.setDocument (\fBDocument\fPdocument)"
Setter of the document 
.PP
\fBParameters:\fP
.RS 4
\fIdocument\fP the document that have to be set 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.mapping\&.Represents\&.setVariable (\fBVariable\fPvariable)"
Setter of the variable 
.PP
\fBParameters:\fP
.RS 4
\fIvariable\fP the variable that have to be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
