.TH "eu.aniketos.wp4.SRS.Trustworthiness" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.Trustworthiness \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeu\&.aniketos\&.wp4\&.SRS\&.SecurityNeed\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrustworthiness\fP ()"
.br
.ti -1c
.RI "\fBTrustworthiness\fP (\fBGoal\fP goal, \fBActor\fP actor)"
.br
.ti -1c
.RI "Integer \fBgetLevel\fP ()"
.br
.ti -1c
.RI "void \fBsetLevel\fP (Integer level)"
.br
.ti -1c
.RI "\fBGoal\fP \fBgetGoal\fP ()"
.br
.ti -1c
.RI "void \fBsetGoal\fP (\fBGoal\fP goal)"
.br
.ti -1c
.RI "\fBActor\fP \fBgetActor\fP ()"
.br
.ti -1c
.RI "void \fBsetActor\fP (\fBActor\fP actor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the \fBTrustworthiness\fP security requirements 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "eu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\&.Trustworthiness ()"
empty constructor of the class 
.SS "eu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\&.Trustworthiness (\fBGoal\fPgoal, \fBActor\fPactor)"
constructor of the class 
.PP
\fBParameters:\fP
.RS 4
\fIgoal\fP the goal to which the security requirement is linked 
.br
\fIactor\fP the actor to which the security requirement is linked 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBActor\fP eu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\&.getActor ()"
Getter of the goal for the trustworthiness security requirement 
.PP
\fBReturns:\fP
.RS 4
the actor 
.RE
.PP

.SS "\fBGoal\fP eu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\&.getGoal ()"
Getter of the goal for the trustworthiness security requirement 
.PP
\fBReturns:\fP
.RS 4
the goal 
.RE
.PP

.SS "Integer eu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\&.getLevel ()"
\fBReturns:\fP
.RS 4
the level 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\&.setActor (\fBActor\fPactor)"
Setter of the goal for the trustworthiness security requirement 
.PP
\fBParameters:\fP
.RS 4
\fIactor\fP the actor to set 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\&.setGoal (\fBGoal\fPgoal)"
Setter of the goal for the trustworthiness security requirement 
.PP
\fBParameters:\fP
.RS 4
\fIgoal\fP the goal to set 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Trustworthiness\&.setLevel (Integerlevel)"
\fBParameters:\fP
.RS 4
\fIlevel\fP the level to set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
