.TH "eu.aniketos.activiti.Activiti" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.activiti.Activiti \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HashMap< String, 
.br
\fBActivitiNeedToKnow\fP > \fBgetPermissions\fP ()"
.br
.ti -1c
.RI "void \fBsetPermissions\fP (HashMap< String, \fBActivitiNeedToKnow\fP > permissions)"
.br
.ti -1c
.RI "HashMap< String, \fBActivitiRole\fP > \fBgetRoles\fP ()"
.br
.ti -1c
.RI "void \fBsetRoles\fP (HashMap< String, \fBActivitiRole\fP > roles)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class contains all the information contained in \&.activiti file used by SRCM 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "HashMap<String, \fBActivitiNeedToKnow\fP> eu\&.aniketos\&.activiti\&.Activiti\&.getPermissions ()"
\fBReturns:\fP
.RS 4
the permissions 
.RE
.PP

.SS "HashMap<String, \fBActivitiRole\fP> eu\&.aniketos\&.activiti\&.Activiti\&.getRoles ()"
\fBReturns:\fP
.RS 4
the roles 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.Activiti\&.setPermissions (HashMap< String, \fBActivitiNeedToKnow\fP >permissions)"
\fBParameters:\fP
.RS 4
\fIpermissions\fP the permissions to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.Activiti\&.setRoles (HashMap< String, \fBActivitiRole\fP >roles)"
\fBParameters:\fP
.RS 4
\fIroles\fP the roles to set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
