.TH "eu.aniketos.srcm.SRS.NonRepudiation" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.SRS.NonRepudiation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeu\&.aniketos\&.srcm\&.SRS\&.SecurityNeed\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonRepudiation\fP ()"
.br
.ti -1c
.RI "Vector< \fBGoal\fP > \fBgetGoalList\fP ()"
.br
.ti -1c
.RI "void \fBsetGoalList\fP (Vector< \fBGoal\fP > goalList)"
.br
.ti -1c
.RI "void \fBaddGoal\fP (\fBGoal\fP goal)"
.br
.ti -1c
.RI "void \fBremoveGoal\fP (\fBGoal\fP goal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the non repudiation security need 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "eu\&.aniketos\&.srcm\&.SRS\&.NonRepudiation\&.NonRepudiation ()"
Constructor of the class 
.SH "Member Function Documentation"
.PP 
.SS "void eu\&.aniketos\&.srcm\&.SRS\&.NonRepudiation\&.addGoal (\fBGoal\fPgoal)"
This function adds a goal to the goal list 
.PP
\fBParameters:\fP
.RS 4
\fIgoal\fP the goal that has to be added 
.RE
.PP

.SS "Vector<\fBGoal\fP> eu\&.aniketos\&.srcm\&.SRS\&.NonRepudiation\&.getGoalList ()"
Getter of the goal list that cannot be repudiated 
.PP
\fBReturns:\fP
.RS 4
the goal list 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.SRS\&.NonRepudiation\&.removeGoal (\fBGoal\fPgoal)"
This function removes a goal to the goal list 
.PP
\fBParameters:\fP
.RS 4
\fIgoal\fP the goal that has to be removed 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.SRS\&.NonRepudiation\&.setGoalList (Vector< \fBGoal\fP >goalList)"
Setter of the goal list that cannot be repudiated 
.PP
\fBParameters:\fP
.RS 4
\fIgoalList\fP that has to be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
