.TH "eu.aniketos.srcm.SRS.Information" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.SRS.Information \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeu\&.aniketos\&.srcm\&.SRS\&.Resource\fP\&.
.PP
Inherited by \fBeu\&.aniketos\&.SecureBPMN\&.Variable\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class manage the \fBSRS\fP information Element 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
