.TH "eu.aniketos.srcm.functional.NRInst" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.functional.NRInst \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinstantiateCommitment\fP (\fBCommitment\fP commitment, \fBMapping\fP mapping, \fBSRS\fP srs, HashSet< \fBCommitment\fP > undecCommitmentList)"
.br
.in -1c
.SH "Detailed Description"
.PP 
this class manages the Non-Repudiation Instantiation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void eu\&.aniketos\&.srcm\&.functional\&.NRInst\&.instantiateCommitment (\fBCommitment\fPcommitment, \fBMapping\fPmapping, \fBSRS\fPsrs, HashSet< \fBCommitment\fP >undecCommitmentList)\fC [static]\fP"
\fBParameters:\fP
.RS 4
\fIcommitment\fP Commitment to instantiate 
.br
\fImapping\fP the mapping used to instantiate the commitment 
.br
\fIsrs\fP the list of commitment 
.br
\fIundecCommitmentList\fP List of undecidable commitments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
