.TH "eu.aniketos.activiti.ActivitiRole" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.activiti.ActivitiRole \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String id)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "void \fBaddPermissions\fP (\fBActivitiNeedToKnow\fP ntk)"
.br
.ti -1c
.RI "HashSet< \fBActivitiNeedToKnow\fP > \fBgetPermissions\fP ()"
.br
.ti -1c
.RI "void \fBsetPermissions\fP (HashSet< \fBActivitiNeedToKnow\fP > permissions)"
.br
.ti -1c
.RI "String \fBgetPermissionsID\fP ()"
.br
.ti -1c
.RI "void \fBsetPermissionsID\fP (String permissionsID)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the role concepts in activiti files 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void eu\&.aniketos\&.activiti\&.ActivitiRole\&.addPermissions (\fBActivitiNeedToKnow\fPntk)"
\fBParameters:\fP
.RS 4
\fIntk\fP the permissions to add 
.RE
.PP

.SS "String eu\&.aniketos\&.activiti\&.ActivitiRole\&.getId ()"
\fBReturns:\fP
.RS 4
the id 
.RE
.PP

.SS "String eu\&.aniketos\&.activiti\&.ActivitiRole\&.getName ()"
\fBReturns:\fP
.RS 4
the name 
.RE
.PP

.SS "HashSet<\fBActivitiNeedToKnow\fP> eu\&.aniketos\&.activiti\&.ActivitiRole\&.getPermissions ()"
\fBReturns:\fP
.RS 4
the permissions 
.RE
.PP

.SS "String eu\&.aniketos\&.activiti\&.ActivitiRole\&.getPermissionsID ()"
\fBReturns:\fP
.RS 4
the permissionsID 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiRole\&.setId (Stringid)"
\fBParameters:\fP
.RS 4
\fIid\fP the id to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiRole\&.setName (Stringname)"
\fBParameters:\fP
.RS 4
\fIname\fP the name to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiRole\&.setPermissions (HashSet< \fBActivitiNeedToKnow\fP >permissions)"
\fBParameters:\fP
.RS 4
\fIpermissions\fP the permissions to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiRole\&.setPermissionsID (StringpermissionsID)"
\fBParameters:\fP
.RS 4
\fIpermissionsID\fP the permissionsID to set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
