.TH "eu.aniketos.srcm.functional.ParseActivitiDom" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.functional.ParseActivitiDom \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseActivitiDom\fP (\fBDocument\fP activitiDom)"
.br
.ti -1c
.RI "\fBActiviti\fP \fBgetActiviti\fP ()"
.br
.ti -1c
.RI "void \fBsetActiviti\fP (\fBActiviti\fP activiti)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
mattia 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "eu\&.aniketos\&.srcm\&.functional\&.ParseActivitiDom\&.ParseActivitiDom (\fBDocument\fPactivitiDom)"
this class part the activiti XML files 
.PP
\fBParameters:\fP
.RS 4
\fIactivitiDom\fP the document that contain the XML file 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBActiviti\fP eu\&.aniketos\&.srcm\&.functional\&.ParseActivitiDom\&.getActiviti ()"
\fBReturns:\fP
.RS 4
the activiti 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.functional\&.ParseActivitiDom\&.setActiviti (\fBActiviti\fPactiviti)"
\fBParameters:\fP
.RS 4
\fIactiviti\fP the activiti to set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
