.TH "eu.aniketos.wp4.SRS.Commitment" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.Commitment \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActor\fP \fBgetDebtor\fP ()"
.br
.ti -1c
.RI "void \fBsetDebtor\fP (\fBActor\fP debtor)"
.br
.ti -1c
.RI "\fBActor\fP \fBgetCreditor\fP ()"
.br
.ti -1c
.RI "void \fBsetCreditor\fP (\fBActor\fP creditor)"
.br
.ti -1c
.RI "\fBPrecondition\fP \fBgetPrecondition\fP ()"
.br
.ti -1c
.RI "void \fBsetPrecondition\fP (\fBPrecondition\fP precondition)"
.br
.ti -1c
.RI "\fBSecurityNeed\fP \fBgetPostCondition\fP ()"
.br
.ti -1c
.RI "void \fBsetPostCondition\fP (\fBSecurityNeed\fP postCondition)"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the commitment \fBSRS\fP element 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBActor\fP eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.getCreditor ()"
Getter of actor who plays the creditor role in the commitment 
.PP
\fBReturns:\fP
.RS 4
the creditor of the commitment 
.RE
.PP

.SS "\fBActor\fP eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.getDebtor ()"
Getter of actor who plays the debtor role in the commitment 
.PP
\fBReturns:\fP
.RS 4
the debtor of the commitment 
.RE
.PP

.SS "String eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.getId ()"
Getter of the commitment ID 
.PP
\fBReturns:\fP
.RS 4
the commitment id 
.RE
.PP

.SS "\fBSecurityNeed\fP eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.getPostCondition ()"
Getter of the commitment postcondition 
.PP
\fBReturns:\fP
.RS 4
the postcondition of the commitment 
.RE
.PP

.SS "\fBPrecondition\fP eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.getPrecondition ()"
Getter of the commitment precondition 
.PP
\fBReturns:\fP
.RS 4
the precondition of the commitment 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.setCreditor (\fBActor\fPcreditor)"
Setter of the actor who plays the creditor role in the commitment 
.PP
\fBParameters:\fP
.RS 4
\fIcreditor\fP the creditor that has to be set 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.setDebtor (\fBActor\fPdebtor)"
Setter of the actor who plays the debtor role in the commitment 
.PP
\fBParameters:\fP
.RS 4
\fIdebtor\fP the debtor that has to be set 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.setId (Stringid)"
Setter of the commitment ID 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP the commitment ID 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.setPostCondition (\fBSecurityNeed\fPpostCondition)"
Setter of the commitment postcondition 
.PP
\fBParameters:\fP
.RS 4
\fIpostCondition\fP the postcondition of the commitment 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Commitment\&.setPrecondition (\fBPrecondition\fPprecondition)"
Setter of the commitment precondition 
.PP
\fBParameters:\fP
.RS 4
\fIprecondition\fP the precondition of the commitment 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
