.TH "eu.aniketos.SecureBPMN.Variable" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.SecureBPMN.Variable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeu\&.aniketos\&.srcm\&.SRS\&.Information\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the \fBVariable\fP Business Process element\&. It extends information class because at the instantiation phase all information elements will be transformed in Business Process elements 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String eu\&.aniketos\&.SecureBPMN\&.Variable\&.getId ()"
Getter of the resource ID 
.PP
\fBReturns:\fP
.RS 4
the resource ID 
.RE
.PP

.PP
Reimplemented from \fBeu\&.aniketos\&.srcm\&.SRS\&.Resource\fP\&.
.SS "String eu\&.aniketos\&.SecureBPMN\&.Variable\&.getName ()"
Getter of the goal name 
.PP
\fBReturns:\fP
.RS 4
the goal name 
.RE
.PP

.PP
Reimplemented from \fBeu\&.aniketos\&.srcm\&.SRS\&.Resource\fP\&.
.SS "void eu\&.aniketos\&.SecureBPMN\&.Variable\&.setId (Stringid)"
Setter of the resource ID 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP the resource ID 
.RE
.PP

.PP
Reimplemented from \fBeu\&.aniketos\&.srcm\&.SRS\&.Resource\fP\&.
.SS "void eu\&.aniketos\&.SecureBPMN\&.Variable\&.setName (Stringname)"
Setter of the resource name 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP name of the resource 
.RE
.PP

.PP
Reimplemented from \fBeu\&.aniketos\&.srcm\&.SRS\&.Resource\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
