.TH "eu.aniketos.srcm.SRS.TangibleBy" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.SRS.TangibleBy \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocument\fP \fBgetDocument\fP ()"
.br
.ti -1c
.RI "void \fBsetDocument\fP (\fBDocument\fP document)"
.br
.ti -1c
.RI "\fBInformation\fP \fBgetInformation\fP ()"
.br
.ti -1c
.RI "void \fBsetInformation\fP (\fBInformation\fP information)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the \fBSRS\fP Tangible By relation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBDocument\fP eu\&.aniketos\&.srcm\&.SRS\&.TangibleBy\&.getDocument ()"
Getter of the \fBSRS\fP document 
.PP
\fBReturns:\fP
.RS 4
the \fBSRS\fP document 
.RE
.PP

.SS "\fBInformation\fP eu\&.aniketos\&.srcm\&.SRS\&.TangibleBy\&.getInformation ()"
Getter of the information 
.PP
\fBReturns:\fP
.RS 4
the \fBSRS\fP information 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.SRS\&.TangibleBy\&.setDocument (\fBDocument\fPdocument)"
Setter of the \fBSRS\fP document 
.PP
\fBParameters:\fP
.RS 4
\fIdocument\fP the \fBSRS\fP document that has to be set 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.SRS\&.TangibleBy\&.setInformation (\fBInformation\fPinformation)"
Setter of the information 
.PP
\fBParameters:\fP
.RS 4
\fIinformation\fP the \fBSRS\fP information that has to be setted 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
