.TH "eu.aniketos.wp4.SRS.Owns" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.Owns \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActor\fP \fBgetOwner\fP ()"
.br
.ti -1c
.RI "void \fBsetOwner\fP (\fBActor\fP owner)"
.br
.ti -1c
.RI "\fBInformation\fP \fBgetInformation\fP ()"
.br
.ti -1c
.RI "void \fBsetInformation\fP (\fBInformation\fP information)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the \fBSRS\fP \fBOwns\fP Relation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBInformation\fP eu\&.aniketos\&.wp4\&.SRS\&.Owns\&.getInformation ()"
Getter of the information part of the relation 
.PP
\fBReturns:\fP
.RS 4
the information contained in the relation 
.RE
.PP

.SS "\fBActor\fP eu\&.aniketos\&.wp4\&.SRS\&.Owns\&.getOwner ()"
Getter of the owner part of the relation 
.PP
\fBReturns:\fP
.RS 4
the owner of the relation 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Owns\&.setInformation (\fBInformation\fPinformation)"
Setter of the information part of the relation 
.PP
\fBParameters:\fP
.RS 4
\fIinformation\fP that has to be set 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Owns\&.setOwner (\fBActor\fPowner)"
Setter of owner of the relation 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP that has to be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
