.TH "eu.aniketos.wp4.SRS.Precondition" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.Precondition \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBeu\&.aniketos\&.wp4\&.SRS\&.Authorization\fP, and \fBeu\&.aniketos\&.wp4\&.SRS\&.Delegation\fP\&.
.SH "Detailed Description"
.PP 
This class manages the precondition \fBSRS\fP element 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
