.TH "eu.aniketos.SecureBPMN.Gateway.Type" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.SecureBPMN.Gateway.Type \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBINCLUSIVE\fP"
.br
.ti -1c
.RI "\fBEXCLUSIVE\fP"
.br
.ti -1c
.RI "\fBPARALLEL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This enum enlists the possible gateway types \&. 
.SH "Member Data Documentation"
.PP 
.SS "eu\&.aniketos\&.SecureBPMN\&.Gateway\&.Type\&.EXCLUSIVE"
\fBGateway\fP is an exclusive gateway\&. 
.SS "eu\&.aniketos\&.SecureBPMN\&.Gateway\&.Type\&.INCLUSIVE"
\fBGateway\fP is an inclusive gateway\&. 
.SS "eu\&.aniketos\&.SecureBPMN\&.Gateway\&.Type\&.PARALLEL"
\fBGateway\fP is an exclusive gateway\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
