.TH "eu.aniketos.srcm.algorithms.SecReqCheck" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.algorithms.SecReqCheck \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBeu\&.aniketos\&.srcm\&.algorithms\&.NDCheck\fP, and \fBeu\&.aniketos\&.srcm\&.algorithms\&.NRCheck\fP\&.
.SH "Detailed Description"
.PP 
Abstract class that will be extended by every class which checks security compliance 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
