.TH "eu.aniketos.activiti.ActivitiNeedToKnow.Permission" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.activiti.ActivitiNeedToKnow.Permission \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBREAD\fP"
.br
.ti -1c
.RI "\fBWRITE\fP"
.br
.ti -1c
.RI "\fBREAD_WRITE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Mattia Salnitri
.RE
.PP
enum type for the CSVM permissions 
.SH "Member Data Documentation"
.PP 
.SS "eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.Permission\&.READ"
Read permission 
.SS "eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.Permission\&.READ_WRITE"
Read and write permissions 
.SS "eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.Permission\&.WRITE"
Write permission 

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
