.TH "eu.aniketos.wp4.SRS.Authorization.Operation" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.Authorization.Operation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUSE\fP"
.br
.ti -1c
.RI "\fBPRODUCE\fP"
.br
.ti -1c
.RI "\fBMODIFY\fP"
.br
.ti -1c
.RI "\fBDISTRIBUTE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This enum enlists the possible authorization types \&. 
.SH "Member Data Documentation"
.PP 
.SS "eu\&.aniketos\&.wp4\&.SRS\&.Authorization\&.Operation\&.DISTRIBUTE"
\fBAuthorization\fP is a DISTRIBUTE authorization \&. 
.SS "eu\&.aniketos\&.wp4\&.SRS\&.Authorization\&.Operation\&.MODIFY"
\fBAuthorization\fP is a MODIFY authorization \&. 
.SS "eu\&.aniketos\&.wp4\&.SRS\&.Authorization\&.Operation\&.PRODUCE"
\fBAuthorization\fP is a PRODUCE authorization \&. 
.SS "eu\&.aniketos\&.wp4\&.SRS\&.Authorization\&.Operation\&.USE"
\fBAuthorization\fP is a USE authorization \&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
