.TH "eu.aniketos.activiti.ActivitiNeedToKnow" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.activiti.ActivitiNeedToKnow \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBPermission\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPermission\fP \fBgetPermission\fP ()"
.br
.ti -1c
.RI "void \fBsetPermission\fP (\fBPermission\fP permission)"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String id)"
.br
.ti -1c
.RI "\fBActivitiRole\fP \fBgetActivitiRole\fP ()"
.br
.ti -1c
.RI "void \fBsetActivitiRole\fP (\fBActivitiRole\fP activitiRole)"
.br
.ti -1c
.RI "String \fBgetVariable\fP ()"
.br
.ti -1c
.RI "void \fBsetVariable\fP (String variable)"
.br
.ti -1c
.RI "String \fBgetTaskID\fP ()"
.br
.ti -1c
.RI "void \fBsetTaskID\fP (String taskID)"
.br
.ti -1c
.RI "String \fBgetActivitiRoleID\fP ()"
.br
.ti -1c
.RI "void \fBsetActivitiRoleID\fP (String activitiRoleID)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the need to know concepts in activiti files 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBActivitiRole\fP eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.getActivitiRole ()"
\fBReturns:\fP
.RS 4
the activitiRole 
.RE
.PP

.SS "String eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.getActivitiRoleID ()"
\fBReturns:\fP
.RS 4
the activitiRoleID 
.RE
.PP

.SS "String eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.getId ()"
\fBReturns:\fP
.RS 4
the id 
.RE
.PP

.SS "\fBPermission\fP eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.getPermission ()"
\fBReturns:\fP
.RS 4
the permission 
.RE
.PP

.SS "String eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.getTaskID ()"
\fBReturns:\fP
.RS 4
the taskID 
.RE
.PP

.SS "String eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.getVariable ()"
\fBReturns:\fP
.RS 4
the variable 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.setActivitiRole (\fBActivitiRole\fPactivitiRole)"
\fBParameters:\fP
.RS 4
\fIactivitiRole\fP the activitiRole to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.setActivitiRoleID (StringactivitiRoleID)"
\fBParameters:\fP
.RS 4
\fIactivitiRoleID\fP the activitiRoleID to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.setId (Stringid)"
\fBParameters:\fP
.RS 4
\fIid\fP the id to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.setPermission (\fBPermission\fPpermission)"
\fBParameters:\fP
.RS 4
\fIpermission\fP the permission to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.setTaskID (StringtaskID)"
\fBParameters:\fP
.RS 4
\fItaskID\fP the taskID to set 
.RE
.PP

.SS "void eu\&.aniketos\&.activiti\&.ActivitiNeedToKnow\&.setVariable (Stringvariable)"
\fBParameters:\fP
.RS 4
\fIvariable\fP the variable to set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
