.TH "eu.aniketos.srcm.SRS.FullyAuthorized" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.SRS.FullyAuthorized \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActor\fP \fBgetOwner\fP ()"
.br
.ti -1c
.RI "void \fBsetOwner\fP (\fBActor\fP owner)"
.br
.ti -1c
.RI "\fBInformation\fP \fBgetInformation\fP ()"
.br
.ti -1c
.RI "void \fBsetInformation\fP (\fBInformation\fP information)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the Fully-Authorized \fBSRS\fP relation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBInformation\fP eu\&.aniketos\&.srcm\&.SRS\&.FullyAuthorized\&.getInformation ()"
Getter of the information targeted by the relation 
.PP
\fBReturns:\fP
.RS 4
the information targeted 
.RE
.PP

.SS "\fBActor\fP eu\&.aniketos\&.srcm\&.SRS\&.FullyAuthorized\&.getOwner ()"
Getter of the owner (the actor fully authorized) of the resource 
.PP
\fBReturns:\fP
.RS 4
the owner of the resource 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.SRS\&.FullyAuthorized\&.setInformation (\fBInformation\fPinformation)"
Setter of the information targeted by the relation 
.PP
\fBParameters:\fP
.RS 4
\fIinformation\fP the information targeted 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.SRS\&.FullyAuthorized\&.setOwner (\fBActor\fPowner)"
Setter of the owner (the actor fully authorized) of the resource 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP the owner of the resource 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
