.TH "eu.aniketos.SecureBPMN.Event.Type" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.SecureBPMN.Event.Type \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSTART\fP"
.br
.ti -1c
.RI "\fBEND\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This enum enlists the possible event types \&. 
.SH "Member Data Documentation"
.PP 
.SS "eu\&.aniketos\&.SecureBPMN\&.Event\&.Type\&.END"
\fBEvent\fP is a End event\&. 
.SS "eu\&.aniketos\&.SecureBPMN\&.Event\&.Type\&.START"
\fBEvent\fP is a Start event\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
