.TH "eu.aniketos.srcm.mapping.IsA" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.mapping.IsA \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActor\fP \fBgetActor\fP ()"
.br
.ti -1c
.RI "void \fBsetActor\fP (\fBActor\fP actor)"
.br
.ti -1c
.RI "\fBParticipant\fP \fBgetParticipant\fP ()"
.br
.ti -1c
.RI "void \fBsetParticipant\fP (\fBParticipant\fP participant)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the is-a relation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBActor\fP eu\&.aniketos\&.srcm\&.mapping\&.IsA\&.getActor ()"
Getter of the actor 
.PP
\fBReturns:\fP
.RS 4
the actor in the class 
.RE
.PP

.SS "\fBParticipant\fP eu\&.aniketos\&.srcm\&.mapping\&.IsA\&.getParticipant ()"
Getter of the participant 
.PP
\fBReturns:\fP
.RS 4
the participant in the class 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.mapping\&.IsA\&.setActor (\fBActor\fPactor)"
Setter of the actor 
.PP
\fBParameters:\fP
.RS 4
\fIactor\fP that has to be set 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.mapping\&.IsA\&.setParticipant (\fBParticipant\fPparticipant)"
Setter of the participant 
.PP
\fBParameters:\fP
.RS 4
\fIparticipant\fP that has to be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
