.TH "eu.aniketos.wp4.SRS.Goal" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.Goal \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBeu\&.aniketos\&.SecureBPMN\&.Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (String id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manage the \fBSRS\fP goal element 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String eu\&.aniketos\&.wp4\&.SRS\&.Goal\&.getId ()"
Getter of the goal ID 
.PP
\fBReturns:\fP
.RS 4
the goal ID 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Element\fP\&.
.SS "String eu\&.aniketos\&.wp4\&.SRS\&.Goal\&.getName ()"
Getter of the goal name 
.PP
\fBReturns:\fP
.RS 4
the goal name 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Activity\fP\&.
.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Goal\&.setId (Stringid)"
Setter of the goal ID 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP of the goal 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Element\fP\&.
.SS "void eu\&.aniketos\&.wp4\&.SRS\&.Goal\&.setName (Stringname)"
Setter of the goal name 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP of the goal 
.RE
.PP

.PP
Reimplemented in \fBeu\&.aniketos\&.SecureBPMN\&.Activity\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
