.TH "eu.aniketos.srcm.Activator" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.Activator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BundleActivator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP (BundleContext bundleContext)  throws Exception  	"
.br
.ti -1c
.RI "void \fBstop\fP (BundleContext bundleContext)  throws Exception "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Mattia Salnitri
.RE
.PP
*This class is used by CFX-DOSGi, in order to publish the \fBSRCM\fP bundle as an external service 
.SH "Member Function Documentation"
.PP 
.SS "void eu\&.aniketos\&.srcm\&.Activator\&.start (BundleContextbundleContext)  throws Exception  	"
(non-Javadoc) 
.PP
\fBSee also:\fP
.RS 4
org\&.osgi\&.framework\&.BundleActivator::start(org\&.osgi\&.framework\&.BundleContext) 
.RE
.PP

.SS "void eu\&.aniketos\&.srcm\&.Activator\&.stop (BundleContextbundleContext)  throws Exception "
(non-Javadoc) 
.PP
\fBSee also:\fP
.RS 4
org\&.osgi\&.framework\&.BundleActivator::stop(org\&.osgi\&.framework\&.BundleContext) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
