.TH "eu.aniketos.srcm.functional.TWInst" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.srcm.functional.TWInst \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinstantiateCommitment\fP (\fBCommitment\fP commitment, \fBMapping\fP mapping, \fBSRS\fP srs, HashSet< \fBCommitment\fP > undecCommitmentList)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the Trustworthiness Instantiation 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void eu\&.aniketos\&.srcm\&.functional\&.TWInst\&.instantiateCommitment (\fBCommitment\fPcommitment, \fBMapping\fPmapping, \fBSRS\fPsrs, HashSet< \fBCommitment\fP >undecCommitmentList)\fC [static]\fP"
\fBParameters:\fP
.RS 4
\fIcommitment\fP Commitment to instantiate 
.br
\fImapping\fP the mapping used to instantiate the commitment 
.br
\fIsrs\fP the list of commitment 
.br
\fIundecCommitmentList\fP list of undecidable security requirements 
.RE
.PP
i do not search through all the actors that are mapped to 'destination',because this will lead to the creation of 

.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
