.TH "eu.aniketos.wp4.SRS.NonProduction" 3 "Fri Oct 4 2013" "SRCM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eu.aniketos.wp4.SRS.NonProduction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeu\&.aniketos\&.wp4\&.SRS\&.SecurityNeed\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonProduction\fP ()"
.br
.ti -1c
.RI "Vector< \fBInformation\fP > \fBgetInformationList\fP ()"
.br
.ti -1c
.RI "void \fBaddInformation\fP (\fBInformation\fP information)"
.br
.ti -1c
.RI "void \fBremoveInformation\fP (\fBInformation\fP information)"
.br
.ti -1c
.RI "void \fBsetInformationList\fP (Vector< \fBInformation\fP > informationList)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class manages the non production security need 
.PP
\fBAuthor:\fP
.RS 4
Mattia Salnitri 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "eu\&.aniketos\&.wp4\&.SRS\&.NonProduction\&.NonProduction ()"
Constructor of the class 
.SH "Member Function Documentation"
.PP 
.SS "void eu\&.aniketos\&.wp4\&.SRS\&.NonProduction\&.addInformation (\fBInformation\fPinformation)"
This function adds an information to the information list 
.PP
\fBParameters:\fP
.RS 4
\fIinformation\fP the information that has to be added 
.RE
.PP

.SS "Vector<\fBInformation\fP> eu\&.aniketos\&.wp4\&.SRS\&.NonProduction\&.getInformationList ()"
Getter of the information that cannot be produced 
.PP
\fBReturns:\fP
.RS 4
the list of the information 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.NonProduction\&.removeInformation (\fBInformation\fPinformation)"
This function removes an information to the information list 
.PP
\fBParameters:\fP
.RS 4
\fIinformation\fP the information that has to be removed 
.RE
.PP

.SS "void eu\&.aniketos\&.wp4\&.SRS\&.NonProduction\&.setInformationList (Vector< \fBInformation\fP >informationList)"
Setter of the information list 
.PP
\fBParameters:\fP
.RS 4
\fIinformationList\fP the information list that has to be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SRCM from the source code\&.
